name: json_serializable
version: 0.1.0-dev
author: Dart Team <misc@dartlang.org>
description: Generates utilities to aid in serializing to/from JSON.
homepage: https://github.com/dart-lang/json_serialization
environment:
  sdk: '>=1.22.1 <2.0.0-dev.infinity'
dependencies:
  analyzer: '>=0.29.10 <0.31.0'
  build: ^0.9.0
  path: ^1.3.2
  source_gen: ^0.6.1+1
dev_dependencies:
  build_runner: ^0.3.2
  build_test: ^0.6.0
  test: ^0.12.3
