name: json_annotation
version: 2.0.0
description: >-
  Classes and helper functions that support JSON code generation via the
  `json_serializable` package.
homepage: https://github.com/dart-lang/json_serializable
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  analyzer: ^0.34.0
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.4.0'
  source_gen: ^0.9.0
  build_runner: ^1.0.0
