name: json_annotation
version: 0.2.0
description: Annotations for the json_serializable package
homepage: https://github.com/dart-lang/json_serializable
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=1.24.0 <2.0.0'
