name: json_annotation
version: 4.10.0
description: >-
  Classes and helper functions that support JSON code generation via the
  `json_serializable` package.
repository: https://github.com/google/json_serializable.dart/tree/master/json_annotation
topics:
 - json
 - build-runner
 - json-serializable
 - codegen

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  meta: ^1.16.0

#dev_dependencies:
#  build_runner: any
#  json_serializable:
#    path: ../json_serializable
