name: json_annotation
version: 3.0.0-dev
description: >-
  Classes and helper functions that support JSON code generation via the
  `json_serializable` package.
homepage: https://github.com/dart-lang/json_serializable
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.2.0 <3.0.0'

# When changing JsonSerializable class.
# dev_dependencies:
#   build_runner: ^1.0.0
#   json_serializable: ^2.0.0
