name: json_serializable
version: 0.5.7-dev
author: Dart Team <misc@dartlang.org>
description: Generates utilities to aid in serializing to/from JSON.
homepage: https://github.com/dart-lang/json_serializable
environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'
dependencies:
  analyzer: ^0.32.0
  build: '>=0.9.0 <0.13.0'
  build_config: '>=0.2.6 <0.4.0'

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation`. Properly constrains all features it provides.
  json_annotation: '>=0.2.8 <0.2.9'
  meta: ^1.1.0
  path: ^1.3.2
  source_gen: '>=0.8.1 <0.9.0'
dev_dependencies:
  build_runner: ^0.8.0
  build_web_compilers: ^0.4.0+1
  build_test: ">=0.9.0 <0.11.0"
  collection: ^1.14.0
  dart_style: ^1.0.0
  logging: ^0.11.3+1
  test: ^0.12.3
  yaml: ^2.1.13

dependency_overrides:
  json_annotation:
    path: ../json_annotation
