name: json_serializable
version: 4.0.0-nullsafety
description: >-
  Automatically generate code for converting to and from JSON by annotating
  Dart classes.
homepage: https://github.com/google/json_serializable.dart
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: '>=0.39.0 <0.41.0'
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  # For v3 only â€“ allow a wide range since the only change was to REMOVE things
  # from json_annotation
  json_annotation: '>=3.1.0 <3.2.0'
  meta: ^1.3.0-nullsafety.5
  path: ^1.8.0-nullsafety.2
  source_gen: ^0.9.6

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  collection: ^1.14.0
  dart_style: ^1.2.0
  logging: ^0.11.3+1
  pub_semver: ^1.4.0
  source_gen_test: ^0.1.0
  stack_trace: ^1.10.0-nullsafety.5
  test: ^1.16.0-nullsafety.7
  yaml: ^3.0.0-nullsafety.0

dependency_overrides:
  json_annotation:
    path: ../json_annotation

  # For yaml!
  yaml: 3.0.0-nullsafety.0
