name: json_serializable
version: 4.0.3
description: >-
  Automatically generate code for converting to and from JSON by annotating
  Dart classes.
repository: https://github.com/google/json_serializable.dart/tree/master/json_serializable
environment:
  # Keeping this <2.12.0 because the code is not null safe – yet!
  # https://github.com/google/json_serializable.dart/issues/821
  sdk: '>=2.11.99 <3.0.0'

dependencies:
  analyzer: '>=0.41.2 <2.0.0'
  build: ^2.0.0
  build_config: ^0.4.4

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  # For v3 only – allow a wide range since the only change was to REMOVE things
  # from json_annotation
  json_annotation: '>=4.0.0 <4.1.0'
  meta: ^1.3.0
  path: ^1.8.0
  source_gen: ^0.9.9

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  collection: ^1.14.0
  dart_style: ^1.2.0
  logging: ^1.0.0
  pub_semver: ^2.0.0
  source_gen_test: ^0.1.0
  stack_trace: ^1.10.0
  test: ^1.16.0
  yaml: ^3.0.0
