name: json_serializable
version: 6.4.0
description: >-
  Automatically generate code for converting to and from JSON by annotating
  Dart classes.
repository: https://github.com/google/json_serializable.dart/tree/master/json_serializable
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: '>=4.6.0 <6.0.0'
  async: ^2.8.0
  build: ^2.0.0
  build_config: '>=0.4.4 <2.0.0'
  collection: ^1.14.0

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  json_annotation: '>=4.7.0 <4.8.0'
  meta: ^1.3.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
  source_gen: ^1.0.0
  source_helper: ^1.3.0

dev_dependencies:
  _json_serial_shared_test:
    path: ../shared_test
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  dart_style: ^2.0.0
  lints: ^2.0.0
  logging: ^1.0.0
  source_gen_test: ^1.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
  yaml: ^3.0.0
