name: json_serializable
version: 6.12.0-wip
description: >-
  Automatically generate code for converting to and from JSON by annotating
  Dart classes.
repository: https://github.com/google/json_serializable.dart/tree/master/json_serializable
environment:
  sdk: ^3.9.0
topics:
 - json
 - build-runner
 - json-serializable
 - codegen

resolution: workspace

dependencies:
  analyzer: '>=9.0.0 <11.0.0'
  async: ^2.10.0
  build: ^4.0.3
  build_config: ^1.2.0
  dart_style: ^3.1.3

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  json_annotation: '>=4.10.0-0 <4.11.0'
  json_schema: ^5.2.2
  meta: ^1.16.0
  path: ^1.9.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.0.0
  source_gen: ^4.1.1
  source_helper: ^1.3.9

dev_dependencies:
  _json_serial_shared_test:
    path: ../shared_test
  build_runner: ^2.10.4
  build_verify: ^3.0.0
  collection: ^1.19.0
  logging: ^1.2.0
  source_gen_test: ^1.3.3
  test: ^1.27.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
  yaml: ^3.1.3
