name: json_serializable
version: 3.4.0-dev
description: >-
  Automatically generate code for converting to and from JSON by annotating
  Dart classes.
homepage: https://github.com/dart-lang/json_serializable
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: ^0.39.0
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  # For v3 only â€“ allow a wide range since the only change was to REMOVE things
  # from json_annotation
  json_annotation: '>=3.0.0 <3.1.0'
  meta: ^1.1.0
  path: ^1.3.2
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  build_web_compilers: '>=1.0.0 <3.0.0'
  collection: ^1.14.0
  dart_style: ^1.2.0
  logging: ^0.11.3+1
  pub_semver: ^1.4.0
  source_gen_test: ^0.1.0
  test: ^1.6.0
  yaml: ^2.1.13
