name: json_serializable
version: 4.0.0-nullsafety
description: >-
  Automatically generate code for converting to and from JSON by annotating
  Dart classes.
homepage: https://github.com/google/json_serializable.dart
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^0.39.0
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  # For v3 only â€“ allow a wide range since the only change was to REMOVE things
  # from json_annotation
  json_annotation: '>=3.0.0 <3.1.0'
  meta: ^1.1.0
  path: ^1.3.2
  source_gen: ^0.9.6

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  #build_web_compilers: '>=1.0.0 <3.0.0'
  collection: ^1.14.0
  dart_style: ^1.2.0
  logging: ^0.11.3+1
  pub_semver: ^1.4.0
  source_gen_test: ^0.1.0
  test: ^1.6.0
  yaml: ^2.1.13

dependency_overrides:
  json_annotation:
    path: ../json_annotation

  async:
    git: git://github.com/dart-lang/async.git
  boolean_selector:
    git: git://github.com/dart-lang/boolean_selector.git
  charcode:
    git: git://github.com/dart-lang/charcode.git
  collection:
    git: git://github.com/dart-lang/collection.git
  js: ^0.6.3-nullsafety
  matcher:
    git: git://github.com/dart-lang/matcher.git
  meta: ^1.3.0-nullsafety.2
  pedantic:
    git: git://github.com/dart-lang/pedantic.git
  pool:
    git: git://github.com/dart-lang/pool.git
  source_maps:
    git: git://github.com/dart-lang/source_maps.git
  source_map_stack_trace:
    git: git://github.com/dart-lang/source_map_stack_trace.git
  source_span:
    git: git://github.com/dart-lang/source_span.git
  stack_trace:
    git: git://github.com/dart-lang/stack_trace.git
  stream_channel:
    git: git://github.com/dart-lang/stream_channel.git
  string_scanner:
    git: git://github.com/dart-lang/string_scanner.git
  term_glyph:
    git: git://github.com/dart-lang/term_glyph.git
  test_api:
    git:
      url: git://github.com/dart-lang/test.git
      path: pkgs/test_api
  test_core:
    git:
      url: git://github.com/dart-lang/test.git
      path: pkgs/test_core
  test:
    git:
      url: git://github.com/dart-lang/test.git
      path: pkgs/test
  typed_data:
    git: git://github.com/dart-lang/typed_data.git