name: json_serializable
version: 6.9.5
description: >-
  Automatically generate code for converting to and from JSON by annotating
  Dart classes.
repository: https://github.com/google/json_serializable.dart/tree/master/json_serializable
environment:
  sdk: ^3.6.0
topics:
 - json
 - build-runner
 - json-serializable
 - codegen

resolution: workspace

dependencies:
  analyzer: '>=6.9.0 <8.0.0'
  async: ^2.10.0
  build: ^2.4.1
  build_config: ^1.1.0
  collection: ^1.17.0
  dart_style: '>=2.3.7 <4.0.0'

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  json_annotation: '>=4.9.0 <4.10.0'
  meta: ^1.14.0
  path: ^1.9.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.0.0
  source_gen: ^2.0.0
  source_helper: ^1.3.4

dev_dependencies:
  _json_serial_shared_test:
    path: ../shared_test
  build_runner: ^2.4.6
  build_verify: ^3.0.0
  logging: ^1.0.0
  source_gen_test: ^1.0.6
  test: ^1.24.4
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
  yaml: ^3.0.0
