name: _test_yaml
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dev_dependencies:
  _json_serial_shared_test:
    path: ../shared_test
  build_runner: ^2.2.1
  build_verify: ^3.0.0
  checked_yaml: ^2.0.4-wip
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  path: ^1.8.2
  test: ^1.21.6
  yaml: ^3.0.0
