name: _test_yaml
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  test: ^1.6.0

  # Repo packages
  checked_yaml: any
  json_annotation: any
  json_serializable: any

dependency_overrides:
  checked_yaml:
    path: ../checked_yaml
  json_annotation:
    path: ../json_annotation
  json_serializable:
    path: ../json_serializable
