name: _test_yaml
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dev_dependencies:
  _json_serial_shared_test:
    path: ../shared_test
  build_runner: ^2.10.4
  build_verify: ^3.0.0
  checked_yaml: ^2.0.4
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  path: ^1.9.0
  test: ^1.27.0
  yaml: ^3.1.3
