name: _test_yaml
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^2.0.0
  checked_yaml: any
  json_annotation: any
  json_serializable: any
  test: ^1.6.0
  yaml: ^3.0.0

dependency_overrides:
  checked_yaml:
    path: ../checked_yaml
  json_annotation:
    path: ../json_annotation
  json_serializable:
    path: ../json_serializable
