name: _test_yaml
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  _json_serial_shared_test:
    path: ../shared_test
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  checked_yaml: any
  json_annotation: ^4.4.0
  json_serializable: any
  lints: ^2.0.0
  path: ^1.8.2
  test: ^1.6.0
  yaml: ^3.0.0

dependency_overrides:
  checked_yaml:
    path: ../checked_yaml
  json_annotation:
    path: ../json_annotation
  json_serializable:
    path: ../json_serializable
