name: checked_yaml
version: 1.0.3-dev
description: >-
  Generate more helpful exceptions when decoding YAML documents using
  package:json_serializable and package:yaml.
homepage: https://github.com/dart-lang/json_serializable
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  json_annotation: '>=2.2.0 <4.0.0'
  source_span: ^1.0.0
  yaml: ^2.1.13

dev_dependencies:
  json_serializable: ^3.0.0
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  path: ^1.0.0
  test: ^1.6.0
  test_process: ^1.0.1
