name: checked_yaml
version: 1.9.0-nullsafety-dev
description: >-
  Generate more helpful exceptions when decoding YAML documents using
  package:json_serializable and package:yaml.
homepage: https://github.com/google/json_serializable.dart
environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  json_annotation: '>=2.2.0 <4.0.0'
  source_span: ^1.8.0-nullsafety.4
  yaml: ^3.0.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  json_serializable: ^3.0.0
  path: ^1.0.0
  test: ^1.16.0-nullsafety.7
  test_process: ^1.0.1

dependency_overrides:
  analyzer: ^0.41.0
  build_config:
    path: /Users/kevmoo/github/build/build_config
  json_annotation:
    path: ../json_annotation
  json_serializable:
    path: ../json_serializable
  # For yaml!
  yaml: 3.0.0-nullsafety.0
