name: checked_yaml
version: 2.0.4

description: >-
  Generate more helpful exceptions when decoding YAML documents using
  package:json_serializable and package:yaml.
repository: https://github.com/google/json_serializable.dart/tree/master/checked_yaml
topics:
 - yaml
 - json
 - build-runner
 - json-serializable
 - codegen

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  json_annotation: ^4.3.0
  source_span: ^1.8.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.6
  build_verify: ^3.0.0
  json_serializable: ^6.0.0
  path: ^1.8.0
  test: ^1.17.10
  test_process: ^2.0.0
