MD004: # bullet format
  style: dash
MD013: false # long lines
MD024: false # multiple headers with the same content
MD025: false # Multiple top level headings in the same document
MD026: false # Trailing punctuation in header
MD028: false # Blank line inside blockquote
MD033: false # disallow in-line HTML
MD041: false # require heading at top of file
MD045: false # image alt text
